spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/abc?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    #初始化大小
    initial-size: 8
    #连接池最小值
    min-idle: 8
    #连接池最大值
    max-active: 12
    #配置获取连接等待超时的时间(单位：毫秒)
    max-wait: 60000
mybatis:
  type-aliases-package: com.shaber.bookmanager.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8080
